Converted mapogr.cpp to use OGR C API instead of C++ classes to allow GDAL/OGR updates without having to recompile MapServer (545)
git-svn-id: http://svn.osgeo.org/mapserver/trunk@7168 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9546,6 +9546,9 @@ echo "${ECHO_T}        OGR support not requested." >&6
 fi
 
 
+
+unset ac_cv_lib_gdal_OGR_SM_Create
+
 echo "$as_me:$LINENO: checking if GDAL support requested" >&5
 echo $ECHO_N "checking if GDAL support requested... $ECHO_C" >&6
 
@@ -9643,6 +9646,75 @@ if test -n "$GDAL_ENABLED" -o "$OGR_ENABLED"; then
 
   GDAL_LIB=`$GDAL_CONFIG --libs`' '`$GDAL_CONFIG --dep-libs`
   GDAL_INC=`$GDAL_CONFIG --cflags`
+
+        echo "$as_me:$LINENO: checking for OGR_SM_Create in -lgdal" >&5
+echo $ECHO_N "checking for OGR_SM_Create in -lgdal... $ECHO_C" >&6
+if test "${ac_cv_lib_gdal_OGR_SM_Create+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgdal $GDAL_LIB $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char OGR_SM_Create ();
+int
+main ()
+{
+OGR_SM_Create ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_gdal_OGR_SM_Create=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_gdal_OGR_SM_Create=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_gdal_OGR_SM_Create" >&5
+echo "${ECHO_T}$ac_cv_lib_gdal_OGR_SM_Create" >&6
+if test $ac_cv_lib_gdal_OGR_SM_Create = yes; then
+  OGRSTYLE="-DHAVE_OGRSTYLE_C"
+fi
+
+  OGR_ENABLED="$OGR_ENABLED $OGRSTYLE"
 
 fi
 
