Fixed AC_MSG_RESULT output for --with-apache
git-svn-id: http://svn.osgeo.org/mapserver/trunk@199 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3576,9 +3576,9 @@ echo "configure:3563: checking for location of Apache headers" >&5
   test -f $APACHE_DIR/src/include/httpd.h && APACHE_INC_DIR="$APACHE_DIR/src/include"
   if test -n "$APACHE_INC_DIR" ; then
     APACHE_INC="-I$APACHE_INC_DIR $APACHE_INC"
-    echo "$ac_t"""-I$APACHE_INC"" 1>&6
+    echo "$ac_t"""-I$APACHE_INC_DIR"" 1>&6
   else
-      { echo "configure: error: "Could not find httpd.h in $APACHE_DIR."" 1>&2; exit 1; }
+    { echo "configure: error: "Could not find httpd.h in $APACHE_DIR."" 1>&2; exit 1; }
   fi
 fi
 
