Add -DUSE_LIBXML, and make libxm2 check depend on SOS and WCS. Use @ALL_ENABLED@ in place of individual USE flags in parts of Makefile.in. Some general restructuring and tidying.
git-svn-id: http://svn.osgeo.org/mapserver/trunk@7108 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10002,7 +10002,6 @@ if test "$MY_CONFIG" = "no" ; then
 else
   echo "$as_me:$LINENO: result: yes, user supplied my_config" >&5
 echo "${ECHO_T}yes, user supplied my_config" >&6
-#  AC_MSG_RESULT([yes, user supplied my_config])
   MYGIS_ENABLED=-DUSE_MYGIS
   MYGIS_LIB="`$MY_CONFIG --libs` -lmysqlclient"
 #  MYGIS_LIB="-L/usr/lib/mysql -lmysqlclient"
@@ -10309,19 +10308,27 @@ if test "${with_sos+set}" = set; then
 
 fi;
 
-if test "$with_sos" = "no" ; then
+if test "x$with_sos" != "xyes" ; then
 
-  echo "$as_me:$LINENO: result:         OGC SOS Server support disabled by --without-sos." >&5
-echo "${ECHO_T}        OGC SOS Server support disabled by --without-sos." >&6
+  echo "$as_me:$LINENO: result:         OGC SOS Server support not requested." >&5
+echo "${ECHO_T}        OGC SOS Server support not requested." >&6
 
-elif test -z "$PROJ_ENABLED" ; then
+else
 
-  echo "$as_me:$LINENO: result:         OGC SOS Support not enabled (libxml2 and PROJ4 and OGR required)." >&5
-echo "${ECHO_T}        OGC SOS Support not enabled (libxml2 and PROJ4 and OGR required)." >&6
-
-elif test "$with_sos" = "yes" ; then
+  if test -z "$PROJ_ENABLED" ; then
+    { { echo "$as_me:$LINENO: error:         OGC SOS Support requested, but PROJ.4 required and missing." >&5
+echo "$as_me: error:         OGC SOS Support requested, but PROJ.4 required and missing." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test -z "$OGR_ENABLED" ; then
+    { { echo "$as_me:$LINENO: error:         OGC SOS Support requested, but OGR required and missing." >&5
+echo "$as_me: error:         OGC SOS Support requested, but OGR required and missing." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 
     SOS_REQUESTED="yes"
+  echo "$as_me:$LINENO: result:         OGC SOS Server support requested." >&5
+echo "${ECHO_T}        OGC SOS Server support requested." >&6
 
 fi
 
@@ -10416,6 +10423,7 @@ echo "${ECHO_T}        OGC WFS Client Connections enabled ($WFS_LYR_ENABLED)." >
 
   CURL_INC=`$LIBCURL_CONFIG --cflags`
   CURL_LIB=`$LIBCURL_CONFIG --libs`
+  CURL_ENABLED=-DUSE_CURL
 
 fi
 
@@ -10429,8 +10437,9 @@ ALL_LIB="$CURL_LIB $ALL_LIB"
 
 
 
-{ echo "$as_me:$LINENO: checking for xml2-config..." >&5
-echo "$as_me: checking for xml2-config..." >&6;}
+echo "$as_me:$LINENO: checking for libxml2" >&5
+echo $ECHO_N "checking for libxml2... $ECHO_C" >&6
+
 
 # Check whether --with-xml2-config or --without-xml2-config was given.
 if test "${with_xml2_config+set}" = set; then
@@ -10440,7 +10449,31 @@ fi;
 
 unset ac_cv_path_LIBXML2_CONFIG
 
-if test "$SOS_REQUESTED" = "yes" ; then
+
+if test -z "$with_xml2_config" ; then
+  if test "x$SOS_REQUESTED" = "xyes" ; then
+    with_xml2_config=yes
+    echo "$as_me:$LINENO: result: libxml2 required." >&5
+echo "${ECHO_T}libxml2 required." >&6
+  elif test "x$WCS_SVR_ENABLED" != "x" ; then
+    with_xml2_config=yes
+    echo "$as_me:$LINENO: result: libxml2 requested for WCS Server." >&5
+echo "${ECHO_T}libxml2 requested for WCS Server." >&6
+    echo "$as_me:$LINENO: result:       If unavailable disable using --without-xml2-config," >&5
+echo "${ECHO_T}      If unavailable disable using --without-xml2-config," >&6
+    echo "$as_me:$LINENO: result:       but WCS 1.1 support will be disabled." >&5
+echo "${ECHO_T}      but WCS 1.1 support will be disabled." >&6
+  else
+    with_xml2_config=no
+    echo "$as_me:$LINENO: result: libxml2 not required." >&5
+echo "${ECHO_T}libxml2 not required." >&6
+  fi
+else
+  echo "$as_me:$LINENO: result: --with-xml2-config=$with_xml2_config specified." >&5
+echo "${ECHO_T}--with-xml2-config=$with_xml2_config specified." >&6
+fi
+
+if test "$with_xml2_config" != "no" ; then
 
   if test "`basename xx/$with_xml2_config`" = "xml2-config" ; then
     LIBXML2_CONFIG="$with_xml2_config"
@@ -10488,7 +10521,7 @@ fi
   fi
 
   if test "$LIBXML2_CONFIG" = "no" ; then
-    { { echo "$as_me:$LINENO: error: couldn't find xml2-config, try using --with-xml2-config=PATH" >&5
+   { { echo "$as_me:$LINENO: error: couldn't find xml2-config, try using --with-xml2-config=PATH" >&5
 echo "$as_me: error: couldn't find xml2-config, try using --with-xml2-config=PATH" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -10498,13 +10531,13 @@ echo "$as_me: error: couldn't find xml2-config, try using --with-xml2-config=PAT
   echo "$as_me:$LINENO: result:         found libxml2 version $XML2_VER" >&5
 echo "${ECHO_T}        found libxml2 version $XML2_VER" >&6
 
-  SOS_SVR_ENABLED="-DUSE_SOS_SVR"
   XML2_INC=`$LIBXML2_CONFIG --cflags`
   XML2_LIB=`$LIBXML2_CONFIG --libs`
+  XML2_ENABLED=-DUSE_LIBXML2
 
-  echo "$as_me:$LINENO: result:         OGC SOS Server enabled ($SOS_SVR_ENABLED)." >&5
-echo "${ECHO_T}        OGC SOS Server enabled ($SOS_SVR_ENABLED)." >&6
-
+  if test "$SOS_REQUESTED" = "yes" ; then
+    SOS_SVR_ENABLED="-DUSE_SOS_SVR"
+  fi
 fi
 
 XML2_INC=$XML2_INC
@@ -10515,17 +10548,18 @@ XML2_LIB=$XML2_LIB
 ALL_INC="$XML2_INC $ALL_INC"
 ALL_LIB="$XML2_LIB $ALL_LIB"
 
+
 WMS_LYR_ENABLED=$WMS_LYR_ENABLED
 
 WFS_LYR_ENABLED=$WFS_LYR_ENABLED
 
 SOS_SVR_ENABLED=$SOS_SVR_ENABLED
 
-ALL_ENABLED="$WMS_LYR_ENABLED $WFS_LYR_ENABLED $SOS_SVR_ENABLED $ALL_ENABLED"
 
+ALL_ENABLED="$WMS_LYR_ENABLED $WFS_LYR_ENABLED $SOS_SVR_ENABLED $XML2_ENABLED $CURL_ENABLED $ALL_ENABLED"
 
-{ echo "$as_me:$LINENO: checking whether FastCGI support should be enabled..." >&5
-echo "$as_me: checking whether FastCGI support should be enabled..." >&6;}
+echo "$as_me:$LINENO: checking FastCGI support" >&5
+echo $ECHO_N "checking FastCGI support... $ECHO_C" >&6
 
 # Check whether --with-fastcgi or --without-fastcgi was given.
 if test "${with_fastcgi+set}" = set; then
@@ -10535,10 +10569,13 @@ fi;
 
 if test "$with_fastcgi" = "no" -o "$with_fastcgi" = "" ; then
 
-  echo "$as_me:$LINENO: result:         FastCGI support not enabled." >&5
-echo "${ECHO_T}        FastCGI support not enabled." >&6
+  echo "$as_me:$LINENO: result: not requested." >&5
+echo "${ECHO_T}not requested." >&6
 
 else
+
+  echo "$as_me:$LINENO: result: requested." >&5
+echo "${ECHO_T}requested." >&6
 
   if test "$with_fastcgi" = "yes" ; then
     FASTCGI_INC=""
@@ -12656,8 +12693,6 @@ echo "$as_me:$LINENO: result:   Debug:                     ${REPORT_ENABLE_DEBUG
 echo "${ECHO_T}  Debug:                     ${REPORT_ENABLE_DEBUG}${DEBUG_FLAGS}" >&6
 echo "$as_me:$LINENO: result:   Generic NINT:              ${USE_NINT}" >&5
 echo "${ECHO_T}  Generic NINT:              ${USE_NINT}" >&6
-echo "$as_me:$LINENO: result:   Threading support:         ${THREAD_FLAG}" >&5
-echo "${ECHO_T}  Threading support:         ${THREAD_FLAG}" >&6
 echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
 echo "$as_me:$LINENO: result:  -------------- Renderer Settings --------- " >&5
@@ -12681,14 +12716,29 @@ echo "${ECHO_T}  PDFLib support:            ${PDF_ENABLED}" >&6
 echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
 
+echo "$as_me:$LINENO: result:  -------------- Support Libraries --------- " >&5
+echo "${ECHO_T} -------------- Support Libraries --------- " >&6
+echo "$as_me:$LINENO: result:   Proj.4 support:            ${PROJ_ENABLED}" >&5
+echo "${ECHO_T}  Proj.4 support:            ${PROJ_ENABLED}" >&6
+echo "$as_me:$LINENO: result:   Libxml2 support:           ${XML2_ENABLED}" >&5
+echo "${ECHO_T}  Libxml2 support:           ${XML2_ENABLED}" >&6
+echo "$as_me:$LINENO: result:   Curl support:              ${CURL_ENABLED}" >&5
+echo "${ECHO_T}  Curl support:              ${CURL_ENABLED}" >&6
+echo "$as_me:$LINENO: result:   FastCGI support:           ${FASTCGI_ENABLED}" >&5
+echo "${ECHO_T}  FastCGI support:           ${FASTCGI_ENABLED}" >&6
+echo "$as_me:$LINENO: result:   Threading support:         ${THREAD_FLAG}" >&5
+echo "${ECHO_T}  Threading support:         ${THREAD_FLAG}" >&6
+echo "$as_me:$LINENO: result:   GEOS support:              ${GEOS_ENABLED}" >&5
+echo "${ECHO_T}  GEOS support:              ${GEOS_ENABLED}" >&6
+echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6
+
 echo "$as_me:$LINENO: result:  -------------- Data Format Drivers ------- " >&5
 echo "${ECHO_T} -------------- Data Format Drivers ------- " >&6
 echo "$as_me:$LINENO: result:   native tiff support:       ${TIFF_ENABLED}" >&5
 echo "${ECHO_T}  native tiff support:       ${TIFF_ENABLED}" >&6
 echo "$as_me:$LINENO: result:   PostGIS support:           ${POSTGIS_ENABLED}" >&5
 echo "${ECHO_T}  PostGIS support:           ${POSTGIS_ENABLED}" >&6
-echo "$as_me:$LINENO: result:   Proj.4 support:            ${PROJ_ENABLED}" >&5
-echo "${ECHO_T}  Proj.4 support:            ${PROJ_ENABLED}" >&6
 echo "$as_me:$LINENO: result:   EPPL7 support:             ${EPPL_ENABLED}" >&5
 echo "${ECHO_T}  EPPL7 support:             ${EPPL_ENABLED}" >&6
 echo "$as_me:$LINENO: result:   ArcSDE support:            ${SDE_ENABLED}" >&5
@@ -12697,12 +12747,8 @@ echo "$as_me:$LINENO: result:   OGR support:               ${OGR_ENABLED}" >&5
 echo "${ECHO_T}  OGR support:               ${OGR_ENABLED}" >&6
 echo "$as_me:$LINENO: result:   GDAL support:              ${GDAL_ENABLED}" >&5
 echo "${ECHO_T}  GDAL support:              ${GDAL_ENABLED}" >&6
-echo "$as_me:$LINENO: result:   GEOS support:              ${GEOS_ENABLED}" >&5
-echo "${ECHO_T}  GEOS support:              ${GEOS_ENABLED}" >&6
 echo "$as_me:$LINENO: result:   Oracle Spatial support:    ${ORACLESPATIAL_ENABLED}" >&5
 echo "${ECHO_T}  Oracle Spatial support:    ${ORACLESPATIAL_ENABLED}" >&6
-echo "$as_me:$LINENO: result:   FastCGI support:           ${FASTCGI_ENABLED}" >&5
-echo "${ECHO_T}  FastCGI support:           ${FASTCGI_ENABLED}" >&6
 echo "$as_me:$LINENO: result: " >&5
 echo "${ECHO_T}" >&6
 
