Updated configure script to detect and require GEOS 2.2.2+ (#1896)
git-svn-id: http://svn.osgeo.org/mapserver/trunk@6528 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8779,16 +8779,15 @@ if test "${with_geos+set}" = set; then
 
 fi;
 
-if test "$with_geos" = "yes" ; then
+if test -n "$with_geos" -a "$with_geos" != "no" ; then
 
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
-  if test "`basename xx/$with_geos`" = "geos-config" ; then
-    GEOS_CONFIG="$with_geos"
-  fi
+  GEOS_CONFIG=$with_geos
 
-  if test -z "$GEOS_CONFIG" ; then
+  if test "$GEOS_CONFIG" = "yes" ; then
+
     # Extract the first word of "geos-config", so it can be a program name with args.
 set dummy geos-config; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
@@ -8829,43 +8828,57 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
-  fi
 
-  if test "$GEOS_CONFIG" = "no" ; then
-    { { echo "$as_me:$LINENO: error: couldn't find geos-config" >&5
-echo "$as_me: error: couldn't find geos-config" >&2;}
+    if test "$GEOS_CONFIG" = "no" ; then
+      { { echo "$as_me:$LINENO: error: couldn't find geos-config in default path. Please specify full path to geos-config" >&5
+echo "$as_me: error: couldn't find geos-config in default path. Please specify full path to geos-config" >&2;}
    { (exit 1); exit 1; }; }
-  fi
+    fi
 
-  GEOS_ENABLED=-DUSE_GEOS
-
-  GEOS_INCDIR=`$GEOS_CONFIG --includes`
-  GEOS_INC="-I$GEOS_INCDIR"
-  GEOS_LIB="`$GEOS_CONFIG --libs`_c"
-
-  GEOS_ENABLED=$GEOS_ENABLED
-
-  GEOS_INC=$GEOS_INC
-
-  GEOS_LIB=$GEOS_LIB
-
-
-  ALL_ENABLED="$GEOS_ENABLED $ALL_ENABLED"
-  ALL_INC="$GEOS_INC $ALL_INC"
-  ALL_LIB="$GEOS_LIB $ALL_LIB"
-
-elif test -n "$with_geos" -a "$with_geos" != "no" ; then
-
-  GEOS_CONFIG=$with_geos
-
-  if test -f "$GEOS_CONFIG" -a -x "$GEOS_CONFIG" ; then
-    echo "$as_me:$LINENO: result: yes, user supplied geos-config ($GEOS_CONFIG)" >&5
-echo "${ECHO_T}yes, user supplied geos-config ($GEOS_CONFIG)" >&6
+  elif test -f "$GEOS_CONFIG" -a -x "$GEOS_CONFIG" ; then
+    echo "$as_me:$LINENO: result: user supplied geos-config ($GEOS_CONFIG)" >&5
+echo "${ECHO_T}user supplied geos-config ($GEOS_CONFIG)" >&6
   else
     { { echo "$as_me:$LINENO: error: '$GEOS_CONFIG' is not an executable.  Make sure you use --with-geos=/path/to/geos-config" >&5
 echo "$as_me: error: '$GEOS_CONFIG' is not an executable.  Make sure you use --with-geos=/path/to/geos-config" >&2;}
    { (exit 1); exit 1; }; }
   fi
+
+
+  min_geos_version=2.1.3
+
+  echo "$as_me:$LINENO: checking for GEOS version >= $min_geos_version" >&5
+echo $ECHO_N "checking for GEOS version >= $min_geos_version... $ECHO_C" >&6
+
+  geos_major_version=`$GEOS_CONFIG --version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1/'`
+  geos_minor_version=`$GEOS_CONFIG --version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\2/'`
+  geos_micro_version=`$GEOS_CONFIG --version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\3/'`
+
+  req_major=`echo $min_geos_version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\1/'`
+  req_minor=`echo $min_geos_version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\2/'`
+  req_micro=`echo $min_geos_version | \
+       sed 's/\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\).*/\3/'`
+
+  ac_req_version=`expr $req_major \* 100000 \+  $req_minor \* 100 \+ $req_micro`
+  ac_geos_version=`expr $geos_major_version \* 100000 \+  $geos_minor_version \* 100 \+ $geos_micro_version`
+
+  if test $ac_req_version -le $ac_geos_version; then
+     echo "$as_me:$LINENO: result: yes. Found version ${geos_major_version}.${geos_minor_version}.${geos_micro_version}" >&5
+echo "${ECHO_T}yes. Found version ${geos_major_version}.${geos_minor_version}.${geos_micro_version}" >&6
+  else
+     echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+     { { echo "$as_me:$LINENO: error: geos-config reports version ${geos_major_version}.${geos_minor_version}.${geos_micro_version}, need at least $min_geos_version or configure --without-geos" >&5
+echo "$as_me: error: geos-config reports version ${geos_major_version}.${geos_minor_version}.${geos_micro_version}, need at least $min_geos_version or configure --without-geos" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+
+
 
   GEOS_ENABLED=-DUSE_GEOS
 
