Look for OpenGL libs under /usr/lib64 as well (#3724)
git-svn-id: http://svn.osgeo.org/mapserver/trunk@11140 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9912,10 +9912,11 @@ echo "$as_me: error: \"could not find gl.h in $OGL_DIR/include/.\"" >&2;}
   fi
 
   test -f $OGL_DIR/lib/libGL.so -a -f $OGL_DIR/lib/libGLU.so && OGL_LIBDIR="$OGL_DIR/lib"
+  test -f $OGL_DIR/lib64/libGL.so -a -f $OGL_DIR/lib64/libGLU.so && OGL_LIBDIR="$OGL_DIR/lib64"
 
   if test -z "$OGL_LIBDIR" ; then
-      { { echo "$as_me:$LINENO: error: \"could not find libGL or libGLU in $OGL_DIR/lib/.\"" >&5
-echo "$as_me: error: \"could not find libGL or libGLU in $OGL_DIR/lib/.\"" >&2;}
+      { { echo "$as_me:$LINENO: error: \"could not find libGL or libGLU in $OGL_DIR/lib/ or $OGL_DIR/lib64/.\"" >&5
+echo "$as_me: error: \"could not find libGL or libGLU in $OGL_DIR/lib/ or $OGL_DIR/lib64/.\"" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
