Added support in configure script for pkg-config for fribidi2 (#2664)
git-svn-id: http://svn.osgeo.org/mapserver/trunk@7771 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -673,6 +673,7 @@ EGREP
 C_PIC
 STRINGS
 MS_VERSION
+PKG_CONFIG
 FT_BIN
 ZLIB_ENABLED
 ZLIB_INC
@@ -1387,6 +1388,7 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-pkg-config[=PATH]      Include pkg-config support (PATH is path to pkg-config)
   --with-freetype=DIR     GD: Specify where FreeType 2.x is installed (DIR is
                               path to freetype-config program or install dir).
   --with-zlib=DIR         GD,SVG: Specify where zlib is installed (DIR is path
@@ -1434,7 +1436,7 @@ Optional Packages:
   --with-curl-config=PATH Specify path to curl-config.
   --with-xml2-config=PATH Specify path to xml2-config.
   --with-fribidi-config[=ARG] Include FriBidi Support (ARG=yes/path to
-                          fribidi-config)
+                          fribidi-config or fribidi.pc)
   --with-fastcgi=path     Enable FastCGI, point to installed tree.
   --with-httpd            Specify path to 'httpd' executable.
   --with-warnings[=flags] Enable strict warnings (or user defined warnings)
@@ -4970,6 +4972,85 @@ MS_VERSION=`grep MS_VERSION mapserver.h | grep '#define' | cut -d\" -f2`
 echo "${ECHO_T}MapServer Version from mapserver.h: '$MS_VERSION'" >&6; }
 MS_VERSION="$MS_VERSION"
 
+
+
+{ echo "$as_me:$LINENO: checking if pkg-config path is provided" >&5
+echo $ECHO_N "checking if pkg-config path is provided... $ECHO_C" >&6; }
+
+
+# Check whether --with-pkg-config was given.
+if test "${with_pkg_config+set}" = set; then
+  withval=$with_pkg_config;
+fi
+
+
+if test -n "$with_pkg_config" -a "$with_pkg_config" != "no" ; then
+
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+
+  PKG_CONFIG=$with_pkg_config
+else
+  PKG_CONFIG="yes"
+fi
+
+if test "$PKG_CONFIG" = "yes" ; then
+
+   # Extract the first word of "pkg-config", so it can be a program name with args.
+set dummy pkg-config; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_PKG_CONFIG+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PKG_CONFIG in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PKG_CONFIG="$PKG_CONFIG" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_PKG_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_path_PKG_CONFIG" && ac_cv_path_PKG_CONFIG="no"
+  ;;
+esac
+fi
+PKG_CONFIG=$ac_cv_path_PKG_CONFIG
+if test -n "$PKG_CONFIG"; then
+  { echo "$as_me:$LINENO: result: $PKG_CONFIG" >&5
+echo "${ECHO_T}$PKG_CONFIG" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+   if test "$PKG_CONFIG" = "no" ; then
+      { echo "$as_me:$LINENO: result: couldn't find pkg-config in default path. Please specify full path to pkg-config if needed" >&5
+echo "${ECHO_T}couldn't find pkg-config in default path. Please specify full path to pkg-config if needed" >&6; }
+   fi
+
+elif test -f "$PKG_CONFIG" -a -x "$PKG_CONFIG" ; then
+     { echo "$as_me:$LINENO: result: user supplied pkg-config ($PKG_CONFIG)" >&5
+echo "${ECHO_T}user supplied pkg-config ($PKG_CONFIG)" >&6; }
+else
+     { { echo "$as_me:$LINENO: error: '$PKG_CONFIG' is not an executable.  Make sure you use --with-pkg-config=/path/to/pkg-config" >&5
+echo "$as_me: error: '$PKG_CONFIG' is not an executable.  Make sure you use --with-pkg-config=/path/to/pkg-config" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 
 
@@ -11836,6 +11917,7 @@ if test "$with_fribidi_config" = "no" -o "$with_fribidi_config" = "" ; then
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
   FRIBIDI_CONFIG="no"
+
 elif test "$with_fribidi_config" = "yes" ; then
   { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
@@ -11880,6 +11962,21 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
+  $FRIBIDI_PKG_CONFIG = "no"
+  if test "$FRIBIDI_CONFIG" = "no" -a "$PKG_CONFIG" != "no" ; then
+     { echo "$as_me:$LINENO: checking for fribidi pkg-config path" >&5
+echo $ECHO_N "checking for fribidi pkg-config path... $ECHO_C" >&6; }
+     `$PKG_CONFIG --silence-errors --libs fribidi >> /dev/null`
+     if test $? -eq 0 ; then
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+        FRIBIDI_PKG_CONFIG="yes"
+        FRIBIDI_CONFIG="fribidi"
+     else
+       { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+     fi
+  fi
 else
   FRIBIDI_CONFIG=$with_fribidi_config
 fi
@@ -11889,11 +11986,19 @@ if test "$FRIBIDI_CONFIG" = "no" ; then
   FRIBIDI_INC=
   FRIBIDI_LIB=
 else
-  { echo "$as_me:$LINENO: result: yes, user supplied fribidi-config" >&5
+  if test "$FRIBIDI_PKG_CONFIG" = "yes" -o ${FRIBIDI_CONFIG: -3} = ".pc" ; then
+     { echo "$as_me:$LINENO: result: yes, user supplied path to fribidi.pc" >&5
+echo "${ECHO_T}yes, user supplied path to fribidi.pc" >&6; }
+     FRIBIDI_ENABLED="-DUSE_FRIBIDI -DUSE_FRIBIDI2"
+     FRIBIDI_LIB=`$PKG_CONFIG --libs $FRIBIDI_CONFIG`
+     FRIBIDI_INC=`$PKG_CONFIG --cflags $FRIBIDI_CONFIG`
+  else
+     { echo "$as_me:$LINENO: result: yes, user supplied fribidi-config" >&5
 echo "${ECHO_T}yes, user supplied fribidi-config" >&6; }
-  FRIBIDI_ENABLED=-DUSE_FRIBIDI
-  FRIBIDI_LIB=`$FRIBIDI_CONFIG --libs`
-  FRIBIDI_INC=`$FRIBIDI_CONFIG --cflags`
+     FRIBIDI_ENABLED=-DUSE_FRIBIDI
+     FRIBIDI_LIB=`$FRIBIDI_CONFIG --libs`
+     FRIBIDI_INC=`$FRIBIDI_CONFIG --cflags`
+  fi
 fi
 
 FRIBIDI_ENABLED=$FRIBIDI_ENABLED
@@ -13688,6 +13793,7 @@ EGREP!$EGREP$ac_delim
 C_PIC!$C_PIC$ac_delim
 STRINGS!$STRINGS$ac_delim
 MS_VERSION!$MS_VERSION$ac_delim
+PKG_CONFIG!$PKG_CONFIG$ac_delim
 FT_BIN!$FT_BIN$ac_delim
 ZLIB_ENABLED!$ZLIB_ENABLED$ac_delim
 ZLIB_INC!$ZLIB_INC$ac_delim
@@ -13724,7 +13830,6 @@ THREAD_FLAG!$THREAD_FLAG$ac_delim
 THREAD_LIB!$THREAD_LIB$ac_delim
 SDE_ENABLED!$SDE_ENABLED$ac_delim
 SDE_INC!$SDE_INC$ac_delim
-SDE_LIB!$SDE_LIB$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -13766,6 +13871,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+SDE_LIB!$SDE_LIB$ac_delim
 GEOS_CONFIG!$GEOS_CONFIG$ac_delim
 GEOS_ENABLED!$GEOS_ENABLED$ac_delim
 GEOS_INC!$GEOS_INC$ac_delim
@@ -13842,7 +13948,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 74; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 75; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
