Avoid error if one uses --with-ld-shared with CMD no arg... this has no effect but some people still try it
git-svn-id: http://svn.osgeo.org/mapserver/trunk@8021 7532c77e-422f-0410-93f4-f0b67bdd69e2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1444,6 +1444,7 @@ Optional Packages:
                           installed (or a pointer to the full source tree)
                           Required in order to compile the PHP/MapScript
                           module.
+  --with-ld-shared=CMD    Specify link command to use to build shared libs
   --without-ld-shared     Disable shared library support
   --with-apxs[=FILE]      (CURRENTLY DISABLED)
                           Use this option only if building the PHP MapScript
@@ -4790,6 +4791,93 @@ if test $ac_cv_func_strrstr = yes; then
   :
 else
   STRINGS="-DNEED_STRRSTR $STRINGS"
+fi
+
+{ echo "$as_me:$LINENO: checking for strcasestr" >&5
+echo $ECHO_N "checking for strcasestr... $ECHO_C" >&6; }
+if test "${ac_cv_func_strcasestr+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define strcasestr to an innocuous variant, in case <limits.h> declares strcasestr.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define strcasestr innocuous_strcasestr
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char strcasestr (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef strcasestr
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char strcasestr ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_strcasestr || defined __stub___strcasestr
+choke me
+#endif
+
+int
+main ()
+{
+return strcasestr ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_strcasestr=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_strcasestr=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_strcasestr" >&5
+echo "${ECHO_T}$ac_cv_func_strcasestr" >&6; }
+if test $ac_cv_func_strcasestr = yes; then
+  :
+else
+  STRINGS="-DNEED_STRCASESTR $STRINGS"
 fi
 
 { echo "$as_me:$LINENO: checking for strlcat" >&5
@@ -12573,11 +12661,13 @@ if test "${with_ld_shared+set}" = set; then
 fi
 
 
-  if test "$with_ld_shared" != "" ; then
+      if test "$with_ld_shared" != "" -a "$with_ld_shared" != "yes"; then
     if test "$with_ld_shared" = "no" ; then
-      echo "user disabled shared library support."
+      { echo "$as_me:$LINENO: result: user disabled shared library support." >&5
+echo "${ECHO_T}user disabled shared library support." >&6; }
     else
-      echo "using user supplied .so link command ... $with_ld_shared"
+      { echo "$as_me:$LINENO: result: using user supplied .so link command ... $with_ld_shared" >&5
+echo "${ECHO_T}using user supplied .so link command ... $with_ld_shared" >&6; }
     fi
     LD_SHARED="$with_ld_shared"
   fi
@@ -12854,11 +12944,13 @@ if test "${with_ld_shared+set}" = set; then
 fi
 
 
-  if test "$with_ld_shared" != "" ; then
+      if test "$with_ld_shared" != "" -a "$with_ld_shared" != "yes"; then
     if test "$with_ld_shared" = "no" ; then
-      echo "user disabled shared library support."
+      { echo "$as_me:$LINENO: result: user disabled shared library support." >&5
+echo "${ECHO_T}user disabled shared library support." >&6; }
     else
-      echo "using user supplied .so link command ... $with_ld_shared"
+      { echo "$as_me:$LINENO: result: using user supplied .so link command ... $with_ld_shared" >&5
+echo "${ECHO_T}using user supplied .so link command ... $with_ld_shared" >&6; }
     fi
     LD_SHARED="$with_ld_shared"
   fi
